"],"command":["/bin/bash","-c"],"image":"haproxy:latest","name":"haproxy-container","ports":{"containerPort":80}}],"dnsConfig":{"nameservers":["10.99.30.112"]},"dnsPolicy":"None","enableServiceLinks":true,"nodeName":"kube-172","preemptionPolicy":"PreemptLowerPriority","priority":0,"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"default","serviceAccountName":"default","terminationGracePeriodSeconds":30,"tolerations":[{"key":"node.kubernetes.io/not-ready","operator":"Exists","effect":"NoExecute","tolerationSeconds":300},{"key":"node.kubernetes.io/unreachable","operator":"Exists","effect":"NoExecute","tolerationSeconds":300}],"volumes":[{"name":"kube-api-access-zpr5t","projected":{"sources":[{"serviceAccountToken":{"expirationSeconds":3607,"path":"token"}},{"configMap":{"name":"kube-root-ca.crt","items":[{"key":"ca.crt","path":"ca.crt"}]}},{"downwardAPI":{"items":[{"path":"namespace","fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}]}}],"defaultMode":420}}]},"status":{"phase":"Running","conditions":[{"type":"PodReadyToStartContainers","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T09:42:14Z"},{"type":"Initialized","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T09:42:11Z"},{"type":"Ready","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T09:42:14Z"},{"type":"ContainersReady","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T09:42:14Z"},{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T09:42:11Z"}],"hostIP":"141.223.181.172","hostIPs":[{"ip":"141.223.181.172"}],"podIP":"10.244.12.27","podIPs":[{"ip":"10.244.12.27"}],"startTime":"2025-05-29T09:42:11Z","containerStatuses":[{"name":"haproxy-container","state":{"running":{"startedAt":"2025-05-29T09:42:13Z"}},"lastState":{},"ready":true,"restartCount":0,"image":"docker.io/dokken/ubuntu-20.04:latest","imageID":"docker.io/dokken/ubuntu-20.04@sha256:61c700117df72aeeb84838caf8f408be3bdd6e776f1e5696d1fdfeea0c3ca4e0","containerID":"containerd://f9e3aeb1ad3129381436d1e094329ae455d130e3387e70e428ce84c2820fa9eb","started":true}],"qosClass":"Burstable"}}": json: cannot unmarshal object into Go struct field Container.spec.containers.ports of type []v1.ContainerPort","reason":"Invalid","details":{"causes":[{"reason":"FieldValueInvalid","message":"Invalid value: "{"apiVersion":"v1","kind":"Pod","metadata":{"creationTimestamp":"2025-05-29T09:42:11Z","deletionGracePeriodSeconds":30,"deletionTimestamp":"2025-05-29T09:43:48Z","labels":{"app":"haproxy"},"managedFields":[{"manager":"OpenAPI-Generator","operation":"Update","apiVersion":"v1","time":"2025-05-29T09:42:11Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:app":{}}},"f:spec":{"f:containers":{"k:{"name":"haproxy-container"}":{".":{},"f:args":{},"f:command":{},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:resources":{".":{},"f:limits":{".":{},"f:cpu":{},"f:memory":{}},"f:requests":{".":{},"f:cpu":{},"f:memory":{}}},"f:securityContext":{".":{},"f:privileged":{}},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}}},"f:dnsConfig":{".":{},"f:nameservers":{}},"f:dnsPolicy":{},"f:enableServiceLinks":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{}}}},{"manager":"kubelet","operation":"Update","apiVersion":"v1","time":"2025-05-29T09:42:14Z","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:conditions":{"k:{"type":"ContainersReady"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:status":{},"f:type":{}},"k:{"type":"Initialized"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:status":{},"f:type":{}},"k:{"type":"PodReadyToStartContainers"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:status":{},"f:type":{}},"k:{"type":"Ready"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:status":{},"f:type":{}}},"f:containerStatuses":{},"f:hostIP":{},"f:hostIPs":{},"f:phase":{},"f:podIP":{},"f:podIPs":{".":{},"k:{"ip":"10.244.12.27"}":{".":{},"f:ip":{}}},"f:startTime":{}}},"subresource":"status"}],"name":"haproxy-pod","namespace":"llm-config","resourceVersion":"11372666","uid":"d7506c06-cef6-4625-9396-61a8bd69db62"},"spec":{"containers":[{"args":["apt update && apt install -y software-properties-common
"],"command":["/bin/bash","-c"],"image":"haproxy:latest","name":"haproxy-container","ports":{"containerPort":80}}],"dnsConfig":{"nameservers":["10.99.30.112"]},"dnsPolicy":"None","enableServiceLinks":true,"nodeName":"kube-172","preemptionPolicy":"PreemptLowerPriority","priority":0,"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"default","serviceAccountName":"default","terminationGracePeriodSeconds":30,"tolerations":[{"key":"node.kubernetes.io/not-ready","operator":"Exists","effect":"NoExecute","tolerationSeconds":300},{"key":"node.kubernetes.io/unreachable","operator":"Exists","effect":"NoExecute","tolerationSeconds":300}],"volumes":[{"name":"kube-api-access-zpr5t","projected":{"sources":[{"serviceAccountToken":{"expirationSeconds":3607,"path":"token"}},{"configMap":{"name":"kube-root-ca.crt","items":[{"key":"ca.crt","path":"ca.crt"}]}},{"downwardAPI":{"items":[{"path":"namespace","fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}]}}],"defaultMode":420}}]},"status":{"phase":"Running","conditions":[{"type":"PodReadyToStartContainers","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T09:42:14Z"},{"type":"Initialized","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T09:42:11Z"},{"type":"Ready","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T09:42:14Z"},{"type":"ContainersReady","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T09:42:14Z"},{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T09:42:11Z"}],"hostIP":"141.223.181.172","hostIPs":[{"ip":"141.223.181.172"}],"podIP":"10.244.12.27","podIPs":[{"ip":"10.244.12.27"}],"startTime":"2025-05-29T09:42:11Z","containerStatuses":[{"name":"haproxy-container","state":{"running":{"startedAt":"2025-05-29T09:42:13Z"}},"lastState":{},"ready":true,"restartCount":0,"image":"docker.io/dokken/ubuntu-20.04:latest","imageID":"docker.io/dokken/ubuntu-20.04@sha256:61c700117df72aeeb84838caf8f408be3bdd6e776f1e5696d1fdfeea0c3ca4e0","containerID":"containerd://f9e3aeb1ad3129381436d1e094329ae455d130e3387e70e428ce84c2820fa9eb","started":true}],"qosClass":"Burstable"}}": json: cannot unmarshal object into Go struct field Container.spec.containers.ports of type []v1.ContainerPort","field":"patch"}]},"code":422}
]","reason":"Invalid","details":{"name":"firewall-pod","kind":"Pod","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: "BestEffort": Pod QoS is immutable","field":"metadata"},{"reason":"FieldValueForbidden","message":"Forbidden: pod updates may not change fields other than `spec.containers[*].image`,`spec.initContainers[*].image`,`spec.activeDeadlineSeconds`,`spec.tolerations` (only additions to existing tolerations),`spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)
","reason":"Invalid","details":{"name":"firewall-pod","kind":"Pod","causes":[{"reason":"FieldValueForbidden","message":"Forbidden: pod updates may not change fields other than `spec.containers[*].image`,`spec.initContainers[*].image`,`spec.activeDeadlineSeconds`,`spec.tolerations` (only additions to existing tolerations),`spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)
"],"command":["/bin/bash","-c"],"image":"alexellis/nmap","name":"firewall"}],"dnsConfig":{"nameservers":["10.99.30.112"]},"dnsPolicy":"None","enableServiceLinks":true,"nodeName":"kube-172","preemptionPolicy":"PreemptLowerPriority","priority":0,"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"default","serviceAccountName":"default","terminationGracePeriodSeconds":30,"tolerations":[{"key":"node.kubernetes.io/not-ready","operator":"Exists","effect":"NoExecute","tolerationSeconds":300},{"key":"node.kubernetes.io/unreachable","operator":"Exists","effect":"NoExecute","tolerationSeconds":300}],"volumes":[{"name":"kube-api-access-ngnpn","projected":{"sources":[{"serviceAccountToken":{"expirationSeconds":3607,"path":"token"}},{"configMap":{"name":"kube-root-ca.crt","items":[{"key":"ca.crt","path":"ca.crt"}]}},{"downwardAPI":{"items":[{"path":"namespace","fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}]}}],"defaultMode":420}}]},"status":{"phase":"Running","conditions":[{"type":"PodReadyToStartContainers","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T10:59:36Z"},{"type":"Initialized","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T10:59:33Z"},{"type":"Ready","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T10:59:36Z"},{"type":"ContainersReady","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T10:59:36Z"},{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T10:59:33Z"}],"hostIP":"141.223.181.172","hostIPs":[{"ip":"141.223.181.172"}],"podIP":"10.244.12.63","podIPs":[{"ip":"10.244.12.63"}],"startTime":"2025-05-29T10:59:33Z","containerStatuses":[{"name":"firewall-container","state":{"running":{"startedAt":"2025-05-29T10:59:35Z"}},"lastState":{},"ready":true,"restartCount":0,"image":"docker.io/dokken/ubuntu-20.04:latest","imageID":"docker.io/dokken/ubuntu-20.04@sha256:61c700117df72aeeb84838caf8f408be3bdd6e776f1e5696d1fdfeea0c3ca4e0","containerID":"containerd://ce4c18a8d91b6b856f2781c69c8ee502685bc78aecf12c6a4f01d7e78526e0e4","started":true}],"qosClass":"BestEffort"}}": json: cannot unmarshal object into Go struct field Container.spec.containers.ports of type []v1.ContainerPort","reason":"Invalid","details":{"causes":[{"reason":"FieldValueInvalid","message":"Invalid value: "{"apiVersion":"v1","kind":"Pod","metadata":{"creationTimestamp":"2025-05-29T10:59:33Z","deletionGracePeriodSeconds":30,"deletionTimestamp":"2025-05-29T11:02:42Z","managedFields":[{"manager":"OpenAPI-Generator","operation":"Update","apiVersion":"v1","time":"2025-05-29T10:59:33Z","fieldsType":"FieldsV1","fieldsV1":{"f:spec":{"f:containers":{"k:{"name":"firewall-container"}":{".":{},"f:args":{},"f:command":{},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:resources":{},"f:securityContext":{".":{},"f:privileged":{}},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}}},"f:dnsConfig":{".":{},"f:nameservers":{}},"f:dnsPolicy":{},"f:enableServiceLinks":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{}}}},{"manager":"kubelet","operation":"Update","apiVersion":"v1","time":"2025-05-29T10:59:36Z","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:conditions":{"k:{"type":"ContainersReady"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:status":{},"f:type":{}},"k:{"type":"Initialized"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:status":{},"f:type":{}},"k:{"type":"PodReadyToStartContainers"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:status":{},"f:type":{}},"k:{"type":"Ready"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:status":{},"f:type":{}}},"f:containerStatuses":{},"f:hostIP":{},"f:hostIPs":{},"f:phase":{},"f:podIP":{},"f:podIPs":{".":{},"k:{"ip":"10.244.12.63"}":{".":{},"f:ip":{}}},"f:startTime":{}}},"subresource":"status"}],"name":"firewall-pod","namespace":"llm-config","resourceVersion":"11386050","uid":"57ad2958-d31e-41aa-aae1-b1f313c82df5"},"spec":{"containers":[{"args":["apt update && apt install -y software-properties-common
"],"command":["/bin/bash","-c"],"image":"alexellis/nmap","name":"firewall"}],"dnsConfig":{"nameservers":["10.99.30.112"]},"dnsPolicy":"None","enableServiceLinks":true,"nodeName":"kube-172","preemptionPolicy":"PreemptLowerPriority","priority":0,"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"default","serviceAccountName":"default","terminationGracePeriodSeconds":30,"tolerations":[{"key":"node.kubernetes.io/not-ready","operator":"Exists","effect":"NoExecute","tolerationSeconds":300},{"key":"node.kubernetes.io/unreachable","operator":"Exists","effect":"NoExecute","tolerationSeconds":300}],"volumes":[{"name":"kube-api-access-ngnpn","projected":{"sources":[{"serviceAccountToken":{"expirationSeconds":3607,"path":"token"}},{"configMap":{"name":"kube-root-ca.crt","items":[{"key":"ca.crt","path":"ca.crt"}]}},{"downwardAPI":{"items":[{"path":"namespace","fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}]}}],"defaultMode":420}}]},"status":{"phase":"Running","conditions":[{"type":"PodReadyToStartContainers","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T10:59:36Z"},{"type":"Initialized","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T10:59:33Z"},{"type":"Ready","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T10:59:36Z"},{"type":"ContainersReady","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T10:59:36Z"},{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T10:59:33Z"}],"hostIP":"141.223.181.172","hostIPs":[{"ip":"141.223.181.172"}],"podIP":"10.244.12.63","podIPs":[{"ip":"10.244.12.63"}],"startTime":"2025-05-29T10:59:33Z","containerStatuses":[{"name":"firewall-container","state":{"running":{"startedAt":"2025-05-29T10:59:35Z"}},"lastState":{},"ready":true,"restartCount":0,"image":"docker.io/dokken/ubuntu-20.04:latest","imageID":"docker.io/dokken/ubuntu-20.04@sha256:61c700117df72aeeb84838caf8f408be3bdd6e776f1e5696d1fdfeea0c3ca4e0","containerID":"containerd://ce4c18a8d91b6b856f2781c69c8ee502685bc78aecf12c6a4f01d7e78526e0e4","started":true}],"qosClass":"BestEffort"}}": json: cannot unmarshal object into Go struct field Container.spec.containers.ports of type []v1.ContainerPort","field":"patch"}]},"code":422}
","reason":"Invalid","details":{"name":"ndpi-pod","kind":"Pod","causes":[{"reason":"FieldValueForbidden","message":"Forbidden: pod updates may not change fields other than `spec.containers[*].image`,`spec.initContainers[*].image`,`spec.activeDeadlineSeconds`,`spec.tolerations` (only additions to existing tolerations),`spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)
","reason":"Invalid","details":{"name":"suricata-pod","kind":"Pod","causes":[{"reason":"FieldValueForbidden","message":"Forbidden: pod updates may not change fields other than `spec.containers[*].image`,`spec.initContainers[*].image`,`spec.activeDeadlineSeconds`,`spec.tolerations` (only additions to existing tolerations),`spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)
","reason":"Invalid","details":{"name":"ntopng-pod","kind":"Pod","causes":[{"reason":"FieldValueForbidden","message":"Forbidden: pod updates may not change fields other than `spec.containers[*].image`,`spec.initContainers[*].image`,`spec.activeDeadlineSeconds`,`spec.tolerations` (only additions to existing tolerations),`spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)
]","reason":"Invalid","details":{"name":"firewall-pod","kind":"Pod","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: "Burstable": Pod QoS is immutable","field":"metadata"},{"reason":"FieldValueForbidden","message":"Forbidden: pod updates may not change fields other than `spec.containers[*].image`,`spec.initContainers[*].image`,`spec.activeDeadlineSeconds`,`spec.tolerations` (only additions to existing tolerations),`spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)
]","reason":"Invalid","details":{"name":"ndpi-pod","kind":"Pod","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: "nDPI-container": a lowercase RFC 1123 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name', or '123-abc', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?')","field":"spec.containers[0].name"},{"reason":"FieldValueForbidden","message":"Forbidden: pod updates may not change fields other than `spec.containers[*].image`,`spec.initContainers[*].image`,`spec.activeDeadlineSeconds`,`spec.tolerations` (only additions to existing tolerations),`spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)
Err:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 haproxy amd64 2.0.33-0ubuntu0.1
Temporary failure resolving 'archive.ubuntu.com'
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/h/haproxy/haproxy_2.0.33-0ubuntu0.1_amd64.deb Temporary failure resolving 'archive.ubuntu.com'
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
/bin/bash: line 27: haproxy: command not found
Container killed, usually due to out of memory (OOM) or manual termination
Err:12 http://archive.ubuntu.com/ubuntu focal/main amd64 manpages all 5.05-1
Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.39), connection timed out Could not connect to archive.ubuntu.com:80 (185.125.190.81), connection timed out Could not connect to archive.ubuntu.com:80 (185.125.190.82), connection timed out Could not connect to archive.ubuntu.com:80 (185.125.190.36), connection timed out [IP: 185.125.190.39 80]
Err:13 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 python-apt-common all 2.0.1ubuntu0.20.04.1
Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable) [IP: 185.125.190.39 80]
Err:14 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 python3-apt amd64 2.0.1ubuntu0.20.04.1
Err:15 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 python3-distro-info all 0.23ubuntu1.1
Err:24 http://archive.ubuntu.com/ubuntu focal/main amd64 libcrypt-dev amd64 1:4.4.10-10ubuntu4
Err:27 http://archive.ubuntu.com/ubuntu focal/main amd64 libisl22 amd64 0.22.1-1
Err:28 http://archive.ubuntu.com/ubuntu focal/main amd64 libmpfr6 amd64 4.0.2-1
Err:29 http://archive.ubuntu.com/ubuntu focal/main amd64 libmpc3 amd64 1.1.0-1
Err:31 http://archive.ubuntu.com/ubuntu focal/main amd64 cpp amd64 4:9.3.0-1ubuntu2
Err:43 http://archive.ubuntu.com/ubuntu focal/main amd64 gcc amd64 4:9.3.0-1ubuntu2
Err:46 http://archive.ubuntu.com/ubuntu focal/main amd64 g++ amd64 4:9.3.0-1ubuntu2
Err:49 http://archive.ubuntu.com/ubuntu focal/main amd64 patch amd64 2.7.6-6
Err:51 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 build-essential amd64 12.8ubuntu1.1
Err:52 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 cmake-data all 3.16.3-1ubuntu1.20.04.1
Err:54 http://archive.ubuntu.com/ubuntu focal/main amd64 libjsoncpp1 amd64 1.7.4-3.1ubuntu2
Err:55 http://archive.ubuntu.com/ubuntu focal/main amd64 librhash0 amd64 1.3.9-1
Err:56 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 cmake amd64 3.16.3-1ubuntu1.20.04.1
Err:57 http://archive.ubuntu.com/ubuntu focal/main amd64 libdconf1 amd64 0.36.0-1
Err:58 http://archive.ubuntu.com/ubuntu focal/main amd64 dconf-service amd64 0.36.0-1
Err:59 http://archive.ubuntu.com/ubuntu focal/main amd64 dconf-gsettings-backend amd64 0.36.0-1
Err:60 http://archive.ubuntu.com/ubuntu focal/main amd64 libfakeroot amd64 1.24-1
Err:61 http://archive.ubuntu.com/ubuntu focal/main amd64 fakeroot amd64 1.24-1
Err:65 http://archive.ubuntu.com/ubuntu focal/main amd64 liberror-perl all 0.17029-1
Err:71 http://archive.ubuntu.com/ubuntu focal/main amd64 gsettings-desktop-schemas all 3.36.0-1ubuntu1
Err:73 http://archive.ubuntu.com/ubuntu focal/main amd64 libalgorithm-diff-perl all 1.19.03-2
Err:74 http://archive.ubuntu.com/ubuntu focal/main amd64 libalgorithm-diff-xs-perl amd64 0.04-6
Err:75 http://archive.ubuntu.com/ubuntu focal/main amd64 libalgorithm-merge-perl all 0.08-3
Err:77 http://archive.ubuntu.com/ubuntu focal/main amd64 libstemmer0d amd64 0+svn585-2
Err:78 http://archive.ubuntu.com/ubuntu focal/main amd64 libappstream4 amd64 0.12.10-2
Err:79 http://archive.ubuntu.com/ubuntu focal/main amd64 libfile-fcntllock-perl amd64 0.22-3build4
Err:82 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libpcap0.8-dev amd64 1.9.1-3ubuntu1.20.04.1
Err:83 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libpcap-dev amd64 1.9.1-3ubuntu1.20.04.1
Err:85 http://archive.ubuntu.com/ubuntu focal/main amd64 manpages-dev all 5.05-1
Err:89 http://archive.ubuntu.com/ubuntu focal/main amd64 python3-certifi all 2019.11.28-1
Err:90 http://archive.ubuntu.com/ubuntu focal/main amd64 python3-chardet all 3.0.4-4build1
Err:94 http://archive.ubuntu.com/ubuntu focal/main amd64 python3-requests-unixsocket all 0.2.0-2
Err:95 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 python3-software-properties all 0.99.9.12
Err:96 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 software-properties-common all 0.99.9.12
Err:97 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 unattended-upgrades all 2.3ubuntu0.3
Make Error: The source directory "/tmp/nDPI" does not appear to contain CMakeLists.txt.
/bin/bash: line 10: ndpiReader: command not found
/bin/bash: line 9: ndpiReader: command not found
/bin/bash: line 7: ndpiReader: command not found
Err:1 http://archive.ubuntu.com/ubuntu focal InRelease
Err:2 http://security.ubuntu.com/ubuntu focal-security InRelease
Temporary failure resolving 'security.ubuntu.com'
Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.36). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.39). - connect (111: Connection refused) Could not connect to archive.ubuntu.com:80 (185.125.190.83), connection timed out Could not connect to archive.ubuntu.com:80 (185.125.190.82), connection timed out Could not connect to archive.ubuntu.com:80 (185.125.190.81), connection timed out
Err:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable)
Err:3 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Could not connect to archive.ubuntu.com:80 (185.125.190.39). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.83). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.36). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.81). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.82). - connect (111: Connection refused)
Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable)
Err:4 http://security.ubuntu.com/ubuntu focal-security InRelease
Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.82). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.81). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.39). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.83). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.36). - connect (111: Connection refused)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease Could not connect to archive.ubuntu.com:80 (185.125.190.39). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.83). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.36). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.81). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.82). - connect (111: Connection refused)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable)
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.82). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.81). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.39). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.83). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.36). - connect (111: Connection refused)
W: Some index files failed to download. They have been ignored, or old ones used instead.
Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.81). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.82). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.36). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.39). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.83). - connect (111: Connection refused)
Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable)
Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.81). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.83). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.36). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.82). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.39). - connect (111: Connection refused)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.81). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.82). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.36). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.39). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.83). - connect (111: Connection refused)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable)
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.81). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.83). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.36). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.82). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.39). - connect (111: Connection refused)
Err:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.81). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.36). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.39). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.82). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.83). - connect (111: Connection refused)
Err:2 http://archive.ubuntu.com/ubuntu focal InRelease
Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.36). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.81). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.82). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.83). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.39). - connect (111: Connection refused)
Err:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable)
Err:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.36). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.81). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.82). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.83). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.39). - connect (111: Connection refused)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable)
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.81). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.36). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.39). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.82). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.83). - connect (111: Connection refused)
Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.81). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.39). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.82). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.36). - connect (111: Connection refused) Could not connect to archive.ubuntu.com:80 (185.125.190.83). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable)
Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable)
Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.82). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.81). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.36). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.39). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.83). - connect (111: Connection refused)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease Temporary failure resolving 'security.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.81). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.39). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.82). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.36). - connect (111: Connection refused) Could not connect to archive.ubuntu.com:80 (185.125.190.83). - connect (111: Connection refused) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable)
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::101). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.82). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::103). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.81). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::102). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.36). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.39). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.83). - connect (111: Connection refused)
1) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
[ALERT] 148/173939 (311) : Fatal errors found in configuration.
Generral error, likes script failure, invalid arguments, etc.
","reason":"Invalid","details":{"name":"haproxy-pod","kind":"Pod","causes":[{"reason":"FieldValueForbidden","message":"Forbidden: pod updates may not change fields other than `spec.containers[*].image`,`spec.initContainers[*].image`,`spec.activeDeadlineSeconds`,`spec.tolerations` (only additions to existing tolerations),`spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)
4) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
[ALERT] 148/182438 (344) : Fatal errors found in configuration.
/bin/bash: line 8: ndpiReader: command not found
/bin/bash: line 11: ndpiReader: command not found
> -- ERROR: Invalid configuration file.
29/5/2025 -- 20:23:57 - <Error> -- The configuration file must begin with the following two lines: %YAML 1.1 and ---
ERROR: '~ntop' user or team does not exist.
/bin/bash: line 9: ntopng: command not found
[ALERT] 148/210351 (311) : Fatal errors found in configuration.
"],"command":["/bin/bash","-c"],"env":[{"name":"NTOPNG_INTERFACE","value":"eth0"},{"name":"NTOPNG_REPORT_PROTOCOLS","value":"true"}],"image":"dokken/ubuntu-20.04","name":"ntopng","ports":{"containerPort":3000}}],"dnsConfig":{"nameservers":["10.99.30.112"]},"dnsPolicy":"None","enableServiceLinks":true,"nodeName":"kube-167","preemptionPolicy":"PreemptLowerPriority","priority":0,"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"default","serviceAccountName":"default","terminationGracePeriodSeconds":30,"tolerations":[{"key":"node.kubernetes.io/not-ready","operator":"Exists","effect":"NoExecute","tolerationSeconds":300},{"key":"node.kubernetes.io/unreachable","operator":"Exists","effect":"NoExecute","tolerationSeconds":300}],"volumes":[{"name":"kube-api-access-2q877","projected":{"sources":[{"serviceAccountToken":{"expirationSeconds":3607,"path":"token"}},{"configMap":{"name":"kube-root-ca.crt","items":[{"key":"ca.crt","path":"ca.crt"}]}},{"downwardAPI":{"items":[{"path":"namespace","fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}]}}],"defaultMode":420}}]},"status":{"phase":"Pending","conditions":[{"type":"PodReadyToStartContainers","status":"False","lastProbeTime":null,"lastTransitionTime":"2025-05-29T22:17:47Z"},{"type":"Initialized","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T22:17:47Z"},{"type":"Ready","status":"False","lastProbeTime":null,"lastTransitionTime":"2025-05-29T22:17:47Z","reason":"ContainersNotReady","message":"containers with unready status: [ndpi-container]"},{"type":"ContainersReady","status":"False","lastProbeTime":null,"lastTransitionTime":"2025-05-29T22:17:47Z","reason":"ContainersNotReady","message":"containers with unready status: [ndpi-container]"},{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T22:17:47Z"}],"hostIP":"141.223.181.167","hostIPs":[{"ip":"141.223.181.167"}],"startTime":"2025-05-29T22:17:47Z","containerStatuses":[{"name":"ndpi-container","state":{"waiting":{"reason":"ContainerCreating"}},"lastState":{},"ready":false,"restartCount":0,"image":"dokken/ubuntu-20.04","imageID":"","started":false}],"qosClass":"Burstable"}}": json: cannot unmarshal object into Go struct field Container.spec.containers.ports of type []v1.ContainerPort","reason":"Invalid","details":{"causes":[{"reason":"FieldValueInvalid","message":"Invalid value: "{"apiVersion":"v1","kind":"Pod","metadata":{"creationTimestamp":"2025-05-29T22:17:47Z","managedFields":[{"manager":"OpenAPI-Generator","operation":"Update","apiVersion":"v1","time":"2025-05-29T22:17:47Z","fieldsType":"FieldsV1","fieldsV1":{"f:spec":{"f:containers":{"k:{"name":"ndpi-container"}":{".":{},"f:args":{},"f:command":{},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:resources":{".":{},"f:limits":{".":{},"f:cpu":{},"f:memory":{}},"f:requests":{".":{},"f:cpu":{},"f:memory":{}}},"f:securityContext":{".":{},"f:privileged":{}},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}}},"f:dnsConfig":{".":{},"f:nameservers":{}},"f:dnsPolicy":{},"f:enableServiceLinks":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{}}}},{"manager":"kubelet","operation":"Update","apiVersion":"v1","time":"2025-05-29T22:17:47Z","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:conditions":{"k:{"type":"ContainersReady"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{"type":"Initialized"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:status":{},"f:type":{}},"k:{"type":"PodReadyToStartContainers"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:status":{},"f:type":{}},"k:{"type":"Ready"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}},"f:containerStatuses":{},"f:hostIP":{},"f:hostIPs":{},"f:startTime":{}}},"subresource":"status"}],"name":"firewall-pod","namespace":"llm-config","resourceVersion":"11490960","uid":"58fb2579-95bb-45da-a1ea-d963957f0d84"},"spec":{"containers":[{"args":["apt update && apt install -y software-properties-common
"],"command":["/bin/bash","-c"],"env":[{"name":"NTOPNG_INTERFACE","value":"eth0"},{"name":"NTOPNG_REPORT_PROTOCOLS","value":"true"}],"image":"dokken/ubuntu-20.04","name":"ntopng","ports":{"containerPort":3000}}],"dnsConfig":{"nameservers":["10.99.30.112"]},"dnsPolicy":"None","enableServiceLinks":true,"nodeName":"kube-167","preemptionPolicy":"PreemptLowerPriority","priority":0,"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"default","serviceAccountName":"default","terminationGracePeriodSeconds":30,"tolerations":[{"key":"node.kubernetes.io/not-ready","operator":"Exists","effect":"NoExecute","tolerationSeconds":300},{"key":"node.kubernetes.io/unreachable","operator":"Exists","effect":"NoExecute","tolerationSeconds":300}],"volumes":[{"name":"kube-api-access-2q877","projected":{"sources":[{"serviceAccountToken":{"expirationSeconds":3607,"path":"token"}},{"configMap":{"name":"kube-root-ca.crt","items":[{"key":"ca.crt","path":"ca.crt"}]}},{"downwardAPI":{"items":[{"path":"namespace","fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}]}}],"defaultMode":420}}]},"status":{"phase":"Pending","conditions":[{"type":"PodReadyToStartContainers","status":"False","lastProbeTime":null,"lastTransitionTime":"2025-05-29T22:17:47Z"},{"type":"Initialized","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T22:17:47Z"},{"type":"Ready","status":"False","lastProbeTime":null,"lastTransitionTime":"2025-05-29T22:17:47Z","reason":"ContainersNotReady","message":"containers with unready status: [ndpi-container]"},{"type":"ContainersReady","status":"False","lastProbeTime":null,"lastTransitionTime":"2025-05-29T22:17:47Z","reason":"ContainersNotReady","message":"containers with unready status: [ndpi-container]"},{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T22:17:47Z"}],"hostIP":"141.223.181.167","hostIPs":[{"ip":"141.223.181.167"}],"startTime":"2025-05-29T22:17:47Z","containerStatuses":[{"name":"ndpi-container","state":{"waiting":{"reason":"ContainerCreating"}},"lastState":{},"ready":false,"restartCount":0,"image":"dokken/ubuntu-20.04","imageID":"","started":false}],"qosClass":"Burstable"}}": json: cannot unmarshal object into Go struct field Container.spec.containers.ports of type []v1.ContainerPort","field":"patch"}]},"code":422}
[ALERT] 148/222949 (311) : Fatal errors found in configuration.
"],"env":[{"name":"NTOPNG_INTERFACE","value":"eth0"},{"name":"NTOPNG_REPORT_PROTOCOLS","value":"true"}],"image":"dokken/ubuntu-20.04","name":"ntopng","ports":{"containerPort":3000}}],"dnsConfig":{"nameservers":["10.99.30.112"]},"dnsPolicy":"None","enableServiceLinks":true,"nodeName":"kube-172","preemptionPolicy":"PreemptLowerPriority","priority":0,"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"default","serviceAccountName":"default","terminationGracePeriodSeconds":30,"tolerations":[{"key":"node.kubernetes.io/not-ready","operator":"Exists","effect":"NoExecute","tolerationSeconds":300},{"key":"node.kubernetes.io/unreachable","operator":"Exists","effect":"NoExecute","tolerationSeconds":300}],"volumes":[{"name":"kube-api-access-xxtxd","projected":{"sources":[{"serviceAccountToken":{"expirationSeconds":3607,"path":"token"}},{"configMap":{"name":"kube-root-ca.crt","items":[{"key":"ca.crt","path":"ca.crt"}]}},{"downwardAPI":{"items":[{"path":"namespace","fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}]}}],"defaultMode":420}}]},"status":{"phase":"Pending","conditions":[{"type":"PodReadyToStartContainers","status":"False","lastProbeTime":null,"lastTransitionTime":"2025-05-29T22:55:24Z"},{"type":"Initialized","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T22:55:24Z"},{"type":"Ready","status":"False","lastProbeTime":null,"lastTransitionTime":"2025-05-29T22:55:24Z","reason":"ContainersNotReady","message":"containers with unready status: [ndpi-container]"},{"type":"ContainersReady","status":"False","lastProbeTime":null,"lastTransitionTime":"2025-05-29T22:55:24Z","reason":"ContainersNotReady","message":"containers with unready status: [ndpi-container]"},{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T22:55:24Z"}],"hostIP":"141.223.181.172","hostIPs":[{"ip":"141.223.181.172"}],"startTime":"2025-05-29T22:55:24Z","containerStatuses":[{"name":"ndpi-container","state":{"waiting":{"reason":"ContainerCreating"}},"lastState":{},"ready":false,"restartCount":0,"image":"dokken/ubuntu-20.04","imageID":"","started":false}],"qosClass":"Burstable"}}": json: cannot unmarshal object into Go struct field Container.spec.containers.ports of type []v1.ContainerPort","reason":"Invalid","details":{"causes":[{"reason":"FieldValueInvalid","message":"Invalid value: "{"apiVersion":"v1","kind":"Pod","metadata":{"creationTimestamp":"2025-05-29T22:55:24Z","labels":{"app":"ntopng"},"managedFields":[{"manager":"OpenAPI-Generator","operation":"Update","apiVersion":"v1","time":"2025-05-29T22:55:24Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:app":{}}},"f:spec":{"f:containers":{"k:{"name":"ndpi-container"}":{".":{},"f:args":{},"f:command":{},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:resources":{".":{},"f:limits":{".":{},"f:cpu":{},"f:memory":{}},"f:requests":{".":{},"f:cpu":{},"f:memory":{}}},"f:securityContext":{".":{},"f:privileged":{}},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}}},"f:dnsConfig":{".":{},"f:nameservers":{}},"f:dnsPolicy":{},"f:enableServiceLinks":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{}}}},{"manager":"kubelet","operation":"Update","apiVersion":"v1","time":"2025-05-29T22:55:24Z","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:conditions":{"k:{"type":"ContainersReady"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{"type":"Initialized"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:status":{},"f:type":{}},"k:{"type":"PodReadyToStartContainers"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:status":{},"f:type":{}},"k:{"type":"Ready"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}},"f:containerStatuses":{},"f:hostIP":{},"f:hostIPs":{},"f:startTime":{}}},"subresource":"status"}],"name":"ndpi-pod","namespace":"llm-config","resourceVersion":"11496665","uid":"f18b4c22-0fd8-4ffd-9dca-5e124f3cc10e"},"spec":{"containers":[{"command":["/bin/bash","-c","apt update && apt install -y software-properties-common
"],"env":[{"name":"NTOPNG_INTERFACE","value":"eth0"},{"name":"NTOPNG_REPORT_PROTOCOLS","value":"true"}],"image":"dokken/ubuntu-20.04","name":"ntopng","ports":{"containerPort":3000}}],"dnsConfig":{"nameservers":["10.99.30.112"]},"dnsPolicy":"None","enableServiceLinks":true,"nodeName":"kube-172","preemptionPolicy":"PreemptLowerPriority","priority":0,"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"default","serviceAccountName":"default","terminationGracePeriodSeconds":30,"tolerations":[{"key":"node.kubernetes.io/not-ready","operator":"Exists","effect":"NoExecute","tolerationSeconds":300},{"key":"node.kubernetes.io/unreachable","operator":"Exists","effect":"NoExecute","tolerationSeconds":300}],"volumes":[{"name":"kube-api-access-xxtxd","projected":{"sources":[{"serviceAccountToken":{"expirationSeconds":3607,"path":"token"}},{"configMap":{"name":"kube-root-ca.crt","items":[{"key":"ca.crt","path":"ca.crt"}]}},{"downwardAPI":{"items":[{"path":"namespace","fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}]}}],"defaultMode":420}}]},"status":{"phase":"Pending","conditions":[{"type":"PodReadyToStartContainers","status":"False","lastProbeTime":null,"lastTransitionTime":"2025-05-29T22:55:24Z"},{"type":"Initialized","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T22:55:24Z"},{"type":"Ready","status":"False","lastProbeTime":null,"lastTransitionTime":"2025-05-29T22:55:24Z","reason":"ContainersNotReady","message":"containers with unready status: [ndpi-container]"},{"type":"ContainersReady","status":"False","lastProbeTime":null,"lastTransitionTime":"2025-05-29T22:55:24Z","reason":"ContainersNotReady","message":"containers with unready status: [ndpi-container]"},{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2025-05-29T22:55:24Z"}],"hostIP":"141.223.181.172","hostIPs":[{"ip":"141.223.181.172"}],"startTime":"2025-05-29T22:55:24Z","containerStatuses":[{"name":"ndpi-container","state":{"waiting":{"reason":"ContainerCreating"}},"lastState":{},"ready":false,"restartCount":0,"image":"dokken/ubuntu-20.04","imageID":"","started":false}],"qosClass":"Burstable"}}": json: cannot unmarshal object into Go struct field Container.spec.containers.ports of type []v1.ContainerPort","field":"patch"}]},"code":422}
The source directory "/nDPI" does not appear to contain CMakeLists.txt.
fatal: not a git repository (or any of the parent directories): .git
make: *** No rule to make target 'all'. Stop.
cannot stat 'include/ndpi_main.h': No such file or directory
ndpiReader: command not found
ndpiReader: ERROR: Unable to read PCAP file (corrupt?)
cmake: Could not find OpenSSL — required by nDPI
configure: error: libpcap not found
make: *** [src/ndpi_main.o] Error 1
ndpiReader: Segmentation fault (core dumped)
/etc/haproxy/haproxy.cfg:7: unknown keyword 'balancer'
haproxy.service: Failed to start due to configuration error
[ALERT] 007/155631 (3123) : parsing [/etc/haproxy/haproxy.cfg:11] : 'server' : unknown keyword 'weighty'
Permission denied writing to /var/log/haproxy.log
[ALERT] Cannot bind socket [0.0.0.0:80]: Address already in use
[ALERT] 123/221212 (1459): Could not parse configuration file: Missing 'global' section
haproxy.service: ExecStart=/usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg (code=exited, status=1)
SSL support not enabled in this build of HAProxy
Proxy 'backend-app' has no servers available!
Config uses deprecated option 'ssl-default-bind-options'
add-apt-repository: command not found
Configuration error at line 22: unknown keyword 'loggers'
[ERRCODE: SC_ERR_INVALID_ARGUMENT(12)] - pcap file not found
suricata.service: Failed to start due to invalid configuration
[ERRCODE: SC_ERR_NO_RULES(42)] - No rule files found in /etc/suricata/rules
[ERRCODE: SC_ERR_PCAP_CREATE(21)] - Unable to open interface eth0: Permission denied
Failed to set pcap buffer size on eth0
Unknown runmode 'workers'
[ERRCODE: SC_ERR_INVALID_SIGNATURE(28)] - Malformed rule on line 42
No af-packet support compiled in — did you configure with --enable-af-packet?
ntopng requires redis server to be up and running
redis-server: command not found
dpkg: dependency problems prevent configuration of ntopng
ntopng: Invalid license key format
ntopng.service failed to start: Exit code 1
curl: (7) Failed to connect to localhost port 3000: Connection refused
ntopng.log: [ERROR] [Lua] Script failure while initializing interface
ntopng: Could not connect to Redis at 127.0.0.1:6379 — Connection refused
ntopng: Failed to open preferences file: Permission denied
ntopng.service: Main process exited, code=exited, status=1/FAILURE
iptables-persistent not found. Attempting to install via apt...
E: Unable to locate package iptables-persistent
iptables-restore: line 3 failed
iptables: Chain already exists
iptables v1.8.7: unknown option "--dport"
Failed to save iptables rules: Permission denied
iptables-restore: line 12 failed: Invalid argument
iptables: No chain/target/match by that name.
iptables: Resource temporarily unavailable
iptables: Couldn't load target 'MASQUERADE': No such file or directory
Failed to pull image \"myapp:latest\": image not found
CreateContainerConfigError: secrets \"db-credentials\" not found
Invalid value: \"\": must specify a volume type
CrashLoopBackOff: back-off restarting failed container
FailedScheduling: 0/5 nodes are available: insufficient memory.
MountVolume.SetUp failed: configmap \"app-config\" not found
Readiness probe failed: HTTP probe failed with statuscode: 503
liveness probe failed: timeout while waiting for connection
rpc error: code = Unknown desc = failed to create Pod sandbox
container runtime is down, unable to start pod
CrashLoopBackOff: back-off restarting failed container
FailedScheduling: 0/5 nodes are available: insufficient memory.
Readiness probe failed: HTTP probe failed with statuscode: 503
rpc error: code = Unknown desc = failed to create Pod sandbox
iptables-persistent not found. Attempting to install via apt...
iptables-restore: line 3 failed
iptables: Chain already exists
iptables v1.8.7: unknown option "--dport"
iptables: No chain/target/match by that name.
iptables: Resource temporarily unavailable
ntopng: Could not connect to Redis at 127.0.0.1:6379 — Connection refused
add-apt-repository: command not found
[ERRCODE: SC_ERR_NO_RULES(42)] - No rule files found in /etc/suricata/rules
Proxy 'backend-app' has no servers available!
fatal: not a git repository (or any of the parent directories): .git
CrashLoopBackOff: back-off restarting failed container
FailedScheduling: 0/5 nodes are available: insufficient memory.
Readiness probe failed: HTTP probe failed with statuscode: 503
rpc error: code = Unknown desc = failed to create Pod sandbox
iptables-persistent not found. Attempting to install via apt...
iptables-restore: line 3 failed
iptables: Chain already exists
iptables v1.8.7: unknown option "--dport"
iptables: No chain/target/match by that name.
iptables: Resource temporarily unavailable
ntopng: Could not connect to Redis at 127.0.0.1:6379 — Connection refused
add-apt-repository: command not found
[ERRCODE: SC_ERR_NO_RULES(42)] - No rule files found in /etc/suricata/rules
Proxy 'backend-app' has no servers available!
fatal: not a git repository (or any of the parent directories): .git